name: End-to-End Integration Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: ['23.x']
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge
      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        with:
          shell: bash -el {0}
          run: ./scripts/e2e.sh
