name: Test Windows

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: ['23.x', 'latest']
        # vscode-version: ['1.95.3', 'latest']

    runs-on: windows-latest

    steps:
      - name: Install VSCode
        run: choco install vscode
      - run: dir "C:\Program Files\Microsoft VS Code"
      - name: Append vscode to path
        run: echo "C:\Program Files\Microsoft VS Code" >> "$GITHUB_PATH"
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        shell: bash
      - run: npm test
        shell: bash
